name: SyncDocumentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "git@github.com:JoseEduardo/repository_1.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:JoseEduardo/repository_2.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}} # optional
          source_ssh_private_key: ${{secrets.SOURCE_SSH_PRIVATE_KEY}} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{secrets.DESTINATION_SSH_PRIVATE_KEY}}
