name: SyncDocumentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: entrypoint
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "https://github.com/JoseEduardo/repository_1.git"
          source_branch: "main"
          destination_repo: ${{secrets.DESTINATION_REPO}}
          destination_branch: "main"
