name: SyncDocumentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "https://JoseEduardo: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@github.com/JoseEduardo/repository_1.git"
          source_branch: "main"
          destination_repo: "https://JoseEduardo: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@github.com/JoseEduardo/repository_2.git"
          destination_branch: "main"
